# General settings
name: 'graph-tf-model'                   # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'                # online | offline | disabled
gpus: 1                     # Multi-gpu is currently not implemented

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 1
sample_every_val: 1 #val 进行sample的频率
val_check_interval: null
samples_to_generate: 20 #每个template sample的个数
samples_to_save: 20
chains_to_save: 3  #val 保留前n个
log_every_steps: 50
number_chain_steps: 10        # Number of frames in each gif

faster_sampling: 1                              # At each sampling step, set s=t-faster sampling (1 for normal sampling)

final_model_samples_to_save: 10
final_model_chains_to_save: 5 #test 保存top k个

cpus_per_gpu: 4
force_ray: false

evaluate_all_checkpoints: False
num_final_sampling: 5
val_template_num: 200
test_template_num: 200